// Distributed under the MIT software license, see the accompanying
// file LICENSE or http://www.opensource.org/licenses/mit-license.php.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: protos/stakingkeys.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StakingKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       string           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DilithiumInfo []*DilithiumInfo `protobuf:"bytes,2,rep,name=dilithium_info,json=dilithiumInfo,proto3" json:"dilithium_info,omitempty"`
}

func (x *StakingKeys) Reset() {
	*x = StakingKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_stakingkeys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StakingKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakingKeys) ProtoMessage() {}

func (x *StakingKeys) ProtoReflect() protoreflect.Message {
	mi := &file_protos_stakingkeys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakingKeys.ProtoReflect.Descriptor instead.
func (*StakingKeys) Descriptor() ([]byte, []int) {
	return file_protos_stakingkeys_proto_rawDescGZIP(), []int{0}
}

func (x *StakingKeys) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StakingKeys) GetDilithiumInfo() []*DilithiumInfo {
	if x != nil {
		return x.DilithiumInfo
	}
	return nil
}

type DilithiumInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PK      string `protobuf:"bytes,1,opt,name=PK,proto3" json:"PK,omitempty"`
	SK      string `protobuf:"bytes,2,opt,name=SK,proto3" json:"SK,omitempty"`
	HexSeed string `protobuf:"bytes,3,opt,name=hex_seed,json=hexSeed,proto3" json:"hex_seed,omitempty"`
}

func (x *DilithiumInfo) Reset() {
	*x = DilithiumInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_stakingkeys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DilithiumInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DilithiumInfo) ProtoMessage() {}

func (x *DilithiumInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_stakingkeys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DilithiumInfo.ProtoReflect.Descriptor instead.
func (*DilithiumInfo) Descriptor() ([]byte, []int) {
	return file_protos_stakingkeys_proto_rawDescGZIP(), []int{1}
}

func (x *DilithiumInfo) GetPK() string {
	if x != nil {
		return x.PK
	}
	return ""
}

func (x *DilithiumInfo) GetSK() string {
	if x != nil {
		return x.SK
	}
	return ""
}

func (x *DilithiumInfo) GetHexSeed() string {
	if x != nil {
		return x.HexSeed
	}
	return ""
}

var File_protos_stakingkeys_proto protoreflect.FileDescriptor

var file_protos_stakingkeys_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67,
	0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x22, 0x65, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0e, 0x64,
	0x69, 0x6c, 0x69, 0x74, 0x68, 0x69, 0x75, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x69, 0x6c,
	0x69, 0x74, 0x68, 0x69, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x64, 0x69, 0x6c, 0x69,
	0x74, 0x68, 0x69, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4a, 0x0a, 0x0d, 0x44, 0x69, 0x6c,
	0x69, 0x74, 0x68, 0x69, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x50, 0x4b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x50, 0x4b, 0x12, 0x0e, 0x0a, 0x02, 0x53, 0x4b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x53, 0x4b, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x65,
	0x78, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65,
	0x78, 0x53, 0x65, 0x65, 0x64, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x51, 0x52, 0x4c, 0x2f, 0x7a, 0x6f, 0x6e, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_stakingkeys_proto_rawDescOnce sync.Once
	file_protos_stakingkeys_proto_rawDescData = file_protos_stakingkeys_proto_rawDesc
)

func file_protos_stakingkeys_proto_rawDescGZIP() []byte {
	file_protos_stakingkeys_proto_rawDescOnce.Do(func() {
		file_protos_stakingkeys_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_stakingkeys_proto_rawDescData)
	})
	return file_protos_stakingkeys_proto_rawDescData
}

var file_protos_stakingkeys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_stakingkeys_proto_goTypes = []interface{}{
	(*StakingKeys)(nil),   // 0: protos.StakingKeys
	(*DilithiumInfo)(nil), // 1: protos.DilithiumInfo
}
var file_protos_stakingkeys_proto_depIdxs = []int32{
	1, // 0: protos.StakingKeys.dilithium_info:type_name -> protos.DilithiumInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_stakingkeys_proto_init() }
func file_protos_stakingkeys_proto_init() {
	if File_protos_stakingkeys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_stakingkeys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StakingKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_stakingkeys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DilithiumInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_stakingkeys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_stakingkeys_proto_goTypes,
		DependencyIndexes: file_protos_stakingkeys_proto_depIdxs,
		MessageInfos:      file_protos_stakingkeys_proto_msgTypes,
	}.Build()
	File_protos_stakingkeys_proto = out.File
	file_protos_stakingkeys_proto_rawDesc = nil
	file_protos_stakingkeys_proto_goTypes = nil
	file_protos_stakingkeys_proto_depIdxs = nil
}
